[workspace]
channels = ["conda-forge", "bioconda", "https://repo.prefix.dev/almost-conductor"]
name = "plsdescribe"
platforms = ["osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
pillow = ">=11.3.0,<12"
portaudio = ">=19.7.0,<20"
ffmpeg = ">=8.0.0,<9"

[pypi-dependencies]
google-generativeai = ">=0.8.5, <0.9"
google-cloud = ">=0.34.0, <0.35"
pydub = ">=0.25.1, <0.26"
simpleaudio = ">=1.0.4, <2"
google-cloud-texttospeech = ">=2.31.0, <3"
pyaudio = ">=0.2.14, <0.3"
